// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace Picol.Areas.HelpPage.ModelDescriptions
{
    /// <summary>
    /// 
    /// </summary>
    /// <seealso cref="Picol.Areas.HelpPage.ModelDescriptions.ModelDescription" />
    public class KeyValuePairModelDescription : ModelDescription
    {
        /// <summary>Gets or sets the key model description.</summary>
        /// <value>The key model description.</value>
        public ModelDescription KeyModelDescription { get; set; }

        /// <summary>Gets or sets the value model description.</summary>
        /// <value>The value model description.</value>
        public ModelDescription ValueModelDescription { get; set; }
    }
}