//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picol.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    #pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
    public partial class PicolDataLoaderEntities : DbContext
    {
        public PicolDataLoaderEntities()
            : base("name=PicolDataLoaderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int LaunchPicolLoad()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LaunchPicolLoad");
        }
    }
    #pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
}
