//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picol.Models
{
    using System;
    using System.Collections.Generic;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EntityFramework", "1.0.0.0")]
    #pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
    public partial class LabelResult
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string WsdaLineNum { get; set; }
        public string OrPid { get; set; }
        public Nullable<bool> CurrentlyRegisteredWashington { get; set; }
        public Nullable<bool> CurrentlyRegisteredOregon { get; set; }
        public string Epa { get; set; }
        public string EpaOne { get; set; }
        public string EpaTwo { get; set; }
        public string EpaThree { get; set; }
        public string IntendedUser { get; set; }
        public string Ingredients { get; set; }
        public string ResistanceCode { get; set; }
        public string ResistanceSource { get; set; }
        public string Concentrations { get; set; }
        public string PesticideTypes { get; set; }
        public string RegistrantName { get; set; }
        public string Sln { get; set; }
        public string Supplemental { get; set; }
        public string Formulation { get; set; }
        public string SignalWord { get; set; }
        public string Usage { get; set; }
        public string SupplementalName { get; set; }
        public string SupplementalExpiration { get; set; }
        public string SlnName { get; set; }
        public string SlnExpiration { get; set; }
        public Nullable<bool> Spanish { get; set; }
        public Nullable<bool> Organic { get; set; }
        public Nullable<bool> EsaNotice { get; set; }
        public string Section18 { get; set; }
        public string Section18Expiration { get; set; }
        public Nullable<bool> I502 { get; set; }
        public Nullable<bool> Essb { get; set; }
        public string WashingtonDownload { get; set; }
        public string OregonDownload { get; set; }
        public string WashingtonRegistrationYear { get; set; }
        public string OregonRegistrationYear { get; set; }
    }
    #pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
}
