//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picol.Models
{
    using System;
    using System.Collections.Generic;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EntityFramework", "1.0.0.0")]
    #pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
    public partial class Label
    {
        public Label()
        {
            this.LabelFiles = new HashSet<LabelFile>();
            this.IngredientLabelPairs = new HashSet<IngredientLabelPair>();
            this.LabelCropPestTriples = new HashSet<LabelCropPestTriple>();
            this.StateRecords = new HashSet<StateRecord>();
            this.Applications = new HashSet<Application>();
            this.PesticideTypes = new HashSet<PesticideType>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Pid { get; set; }
        public Nullable<int> FormulationId { get; set; }
        public Nullable<int> IntendedUserId { get; set; }
        public Nullable<int> RegistrantId { get; set; }
        public Nullable<int> SignalWordId { get; set; }
        public Nullable<int> UsageId { get; set; }
        public string Name { get; set; }
        public string Supplemental { get; set; }
        public string SupplementalName { get; set; }
        public Nullable<System.DateTime> SupplementalExpiration { get; set; }
        public string Epa { get; set; }
        public string Sln { get; set; }
        public string SlnName { get; set; }
        public Nullable<System.DateTime> SlnExpiration { get; set; }
        public Nullable<bool> Ground { get; set; }
        public Nullable<int> EpaFieldOne { get; set; }
        public Nullable<int> EpaFieldTwo { get; set; }
        public Nullable<int> EpaFieldThree { get; set; }
        public Nullable<bool> Spanish { get; set; }
        public Nullable<bool> Organic { get; set; }
        public string MasterLabel { get; set; }
        public Nullable<bool> EsaNotice { get; set; }
        public string Section18 { get; set; }
        public Nullable<System.DateTime> Section18Expiration { get; set; }
        public string AlsInhib { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<bool> Processed { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Formulation Formulation { get; set; }
        public virtual IntendedUser IntendedUser { get; set; }
        public virtual ICollection<LabelFile> LabelFiles { get; set; }
        public virtual ICollection<IngredientLabelPair> IngredientLabelPairs { get; set; }
        public virtual ICollection<LabelCropPestTriple> LabelCropPestTriples { get; set; }
        public virtual Registrant Registrant { get; set; }
        public virtual SignalWord SignalWord { get; set; }
        public virtual Usage Usage { get; set; }
        public virtual ICollection<StateRecord> StateRecords { get; set; }
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ICollection<PesticideType> PesticideTypes { get; set; }
    }
    #pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
}
