//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picol.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EntityFramework", "1.0.0.0")]
    #pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
    public partial class PicolEntities : DbContext
    {
        public PicolEntities()
            : base("name=PicolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<Crop> Crops { get; set; }
        public virtual DbSet<Formulation> Formulations { get; set; }
        public virtual DbSet<Ingredient> Ingredients { get; set; }
        public virtual DbSet<IntendedUser> IntendedUsers { get; set; }
        public virtual DbSet<Password> Passwords { get; set; }
        public virtual DbSet<Pest> Pests { get; set; }
        public virtual DbSet<Registrant> Registrants { get; set; }
        public virtual DbSet<Resistance> Resistances { get; set; }
        public virtual DbSet<SignalWord> SignalWords { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<IngredientLabelPair> IngredientLabelPairs { get; set; }
        public virtual DbSet<LabelCropPestTriple> LabelCropPestTriples { get; set; }
        public virtual DbSet<Usage> Usages { get; set; }
        public virtual DbSet<RegulationAuthority> RegulationAuthorities { get; set; }
        public virtual DbSet<CropGroup> CropGroups { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<UploadedFile> UploadedFiles { get; set; }
        public virtual DbSet<PesticideType> PesticideTypes { get; set; }
        public virtual DbSet<StateRecord> StateRecords { get; set; }
        public virtual DbSet<LabelFile> LabelFiles { get; set; }
        public virtual DbSet<Label> Labels { get; set; }
        public virtual DbSet<UserPreference> UserPreferences { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<ApiKey> ApiKeys { get; set; }
        public virtual DbSet<BinarySetting> BinarySettings { get; set; }
        public virtual DbSet<LabelResult> LabelResults { get; set; }
        public virtual DbSet<Search> Searches { get; set; }
    
        public virtual int LaunchPicolLoad()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LaunchPicolLoad");
        }
    }
    #pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
}
