//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picol.Models
{
    using System;
    using System.Collections.Generic;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EntityFramework", "1.0.0.0")]
    #pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
    public partial class Resistance
    {
        public Resistance()
        {
            this.Ingredients = new HashSet<Ingredient>();
        }
    
        public int Id { get; set; }
        public string Source { get; set; }
        public string Code { get; set; }
        public string MethodOfAction { get; set; }
        public Nullable<int> Rid { get; set; }
    
        public virtual ICollection<Ingredient> Ingredients { get; set; }
    }
    #pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
}
